/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.main.internal;

import forge.bill.control.DevConnect.ACTION;
import forge.form.common.CommInfoDialog;
import forge.form.binfactory.BinfileMakeForm;
import forge.form.seteia.EIASetupPane;
import forge.bill.platform.ForgeSystem;
import forge.form.debug.DebugPane;
import forge.form.languange.LanguageForm;
import forge.form.common.MainUICenter;
import forge.form.update.UpdateForm;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import nahon.comm.event.Event;
import nahon.comm.event.EventListener;

/**
 *
 * @author jiche
 */
public class MainInternal extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainInternal() {
        initComponents();
        //居中显示
        setLocationRelativeTo(null);
        try {
            this.InitSystem();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "系统初始化失败！ \r\n" + ex.toString());
            Logger.getGlobal().log(Level.SEVERE, null, ex);
            System.exit(0);
        }
    }

    private final CardLayout workScreenLayout = new CardLayout();
    private EIASetupPane eia_setup;

    private void InitSystem() throws Exception {

        //this.setResizable(false);
        MainUICenter.GetInstance().Init(true);

        this.MainAera.setLayout(workScreenLayout);
        this.MainAera.add(BinfileMakeForm.class.getName(), new BinfileMakeForm(this));
        this.MainAera.add(UpdateForm.class.getName(), new UpdateForm(this));
        
        eia_setup = new EIASetupPane(this);
        this.MainAera.add(EIASetupPane.class.getName(), eia_setup);
        this.MainAera.add(DebugPane.class.getName(), new DebugPane());
        this.MainAera.add(InternalAbout.class.getName(), new InternalAbout());
        workScreenLayout.show(this.MainAera, InternalAbout.class.getName());

        ForgeSystem.GetInstance().GetControlCenter().GetConnector().ActionCenter.RegeditListener(new EventListener<ACTION>() {
            @Override
            public void recevieEvent(Event<ACTION> event) {
                SwingUtilities.invokeLater(() -> {
                    if (ACTION.CONNECT == event.GetEvent()) {
                        workScreenLayout.show(MainAera, EIASetupPane.class.getName());
                    }

                    if (ACTION.DISCONNECT == event.GetEvent()) {
                        workScreenLayout.show(MainAera, InternalAbout.class.getName());
                    }
                });
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        MainAera = new javax.swing.JPanel();
        logPane = new forge.form.common.LogPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenDevice = new javax.swing.JMenuItem();
        MenuItem_Close = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menu_Open = new javax.swing.JMenu();
        Menu_EIA = new javax.swing.JMenu();
        Menu_MakeBin = new javax.swing.JMenu();
        Menu_Update = new javax.swing.JMenu();
        Menu_Debug = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forge(Internal)");
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/forge/form/resource/FormIcon.png")));

        javax.swing.GroupLayout MainAeraLayout = new javax.swing.GroupLayout(MainAera);
        MainAera.setLayout(MainAeraLayout);
        MainAeraLayout.setHorizontalGroup(
            MainAeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainAeraLayout.setVerticalGroup(
            MainAeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        jMenu1.setText("打开");

        OpenDevice.setText("搜索新设备");
        OpenDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenDeviceActionPerformed(evt);
            }
        });
        jMenu1.add(OpenDevice);

        MenuItem_Close.setText("关闭");
        MenuItem_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem_CloseMouseClicked(evt);
            }
        });
        MenuItem_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_CloseActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Close);

        jMenuItem1.setText("关于");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        Menu_Open.setText("连接");
        Menu_Open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_OpenMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Open);

        Menu_EIA.setText("设置");
        Menu_EIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_EIAMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_EIA);

        Menu_MakeBin.setText("升级包");
        Menu_MakeBin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_MakeBinMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_MakeBin);

        Menu_Update.setText("升级");
        Menu_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_UpdateMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Update);

        Menu_Debug.setText("调试");
        Menu_Debug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_DebugMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Debug);

        jMenu2.setText("清除");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainAera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logPane, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainAera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logPane, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenDeviceActionPerformed
        CommInfoDialog dilog = new CommInfoDialog(this, true);
        dilog.setVisible(true);
        if (dilog.GetIOInfo() != null) {
            ForgeSystem.GetInstance().GetControlCenter().GetConnector().SearchDevice(dilog.GetIOInfo(), dilog.GetAddr());
        }
    }//GEN-LAST:event_OpenDeviceActionPerformed

    private void Menu_MakeBinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_MakeBinMouseClicked
        workScreenLayout.show(this.MainAera, BinfileMakeForm.class.getName());
    }//GEN-LAST:event_Menu_MakeBinMouseClicked

    private void Menu_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_UpdateMouseClicked
        workScreenLayout.show(this.MainAera, UpdateForm.class.getName());
    }//GEN-LAST:event_Menu_UpdateMouseClicked

    private void Menu_EIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_EIAMouseClicked
        workScreenLayout.show(this.MainAera, EIASetupPane.class.getName());
    }//GEN-LAST:event_Menu_EIAMouseClicked

    private void Menu_OpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_OpenMouseClicked
        ForgeSystem.GetInstance().GetControlCenter().GetConnector().SearchDevice();
    }//GEN-LAST:event_Menu_OpenMouseClicked

    private void MenuItem_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MenuItem_CloseMouseClicked

    private void MenuItem_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_CloseActionPerformed
        ForgeSystem.GetInstance().GetControlCenter().GetConnector().CloseDevice();
    }//GEN-LAST:event_MenuItem_CloseActionPerformed

    private void Menu_DebugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_DebugMouseClicked
        workScreenLayout.show(this.MainAera, DebugPane.class.getName());
    }//GEN-LAST:event_Menu_DebugMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.logPane.ClearLog();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       workScreenLayout.show(this.MainAera, InternalAbout.class.getName());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInternal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//            de.javasoft.plaf.synthetica.
            javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new MainInternal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainAera;
    private javax.swing.JMenuItem MenuItem_Close;
    private javax.swing.JMenu Menu_Debug;
    private javax.swing.JMenu Menu_EIA;
    private javax.swing.JMenu Menu_MakeBin;
    private javax.swing.JMenu Menu_Open;
    private javax.swing.JMenu Menu_Update;
    private javax.swing.JMenuItem OpenDevice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private forge.form.common.LogPane logPane;
    // End of variables declaration//GEN-END:variables
}
