/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.update;

import forge.bill.data.UpdateFileHead;
import forge.bill.platform.ForgeSystem;
import forge.bill.platform.SystemConfig;
import forge.form.binfactory.BinFileHeadModel;
import forge.form.common.InitPaneHelper;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author jiche
 */
public class UpdateForm extends javax.swing.JPanel {

    /**
     * Creates new form UpdateForm
     */
    java.awt.Frame parent = null;

    public UpdateForm(java.awt.Frame parent) {
        this.parent = parent;

        initComponents();

        FileHeadTable.setModel(new BinFileHeadModel(new UpdateFileHead()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        InfoList = new javax.swing.JList();
        DevicePanel = new javax.swing.JPanel();
        eiaTablePane = new javax.swing.JScrollPane();
        FileHeadTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        FileBinPath = new javax.swing.JTextField();
        OpenFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        InfoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(InfoList);

        DevicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("文件信息"));

        FileHeadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        eiaTablePane.setViewportView(FileHeadTable);

        javax.swing.GroupLayout DevicePanelLayout = new javax.swing.GroupLayout(DevicePanel);
        DevicePanel.setLayout(DevicePanelLayout);
        DevicePanelLayout.setHorizontalGroup(
            DevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eiaTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        DevicePanelLayout.setVerticalGroup(
            DevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DevicePanelLayout.createSequentialGroup()
                .addComponent(eiaTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel2.setText("FilePath:");

        FileBinPath.setEditable(false);

        OpenFile.setText("...");
        OpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenFileMouseClicked(evt);
            }
        });
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });

        jButton1.setText("升级");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DevicePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FileBinPath, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DevicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FileBinPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OpenFile)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //获取升级文件
    private void OpenFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenFileMouseClicked

    }//GEN-LAST:event_OpenFileMouseClicked

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        String filepath = InitPaneHelper.GetFilePath(".nuf");
        if (filepath == null) {
            return;
        }

        File file = new File(filepath);
        if (file.exists()) {
            try {
                //获取升级文件头信息
                FileInputStream updatefileStream = new FileInputStream(file);
                byte[] headbuffer = new byte[UpdateFileHead.BinFileHeadLength];
                updatefileStream.read(headbuffer);
                UpdateFileHead updateInfo = new UpdateFileHead(headbuffer);
                //显示升级文件头信息
                BinFileHeadModel model = new BinFileHeadModel(updateInfo);
                model.canModify = false;

                //显示升级包路径
                this.FileBinPath.setText(file.getAbsolutePath());
            } catch (Exception ex) {
                File tmpfile = new File(file.getPath() + ".nuf");
                //if (Boolean.valueOf(SystemConfig.GetInstance().GetValue(SystemConfig.InternalFlag))) {
                //JOptionPane.showMessageDialog(this, "无法读取升级文件!" + ex.toString());
                if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(this, "是否需要自动转换格式?", "", JOptionPane.YES_NO_OPTION)) {
                    //开始制作进程
                    ForgeSystem.GetInstance().GetControlCenter().GetUpdateBean().GetUpdateBuilder().CompressBinFiles(
                            new File[]{file},
                            tmpfile,
                            ((BinFileHeadModel) this.FileHeadTable.getModel()).GetFileHead());
                    //显示升级包路径
                    this.FileBinPath.setText(tmpfile.getAbsolutePath());
                }
                //}
            }
        }
    }//GEN-LAST:event_OpenFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File file = new File(this.FileBinPath.getText());
        if (file.exists()) {
            ForgeSystem.GetInstance().GetControlCenter().GetUpdateBean().UpdateFile(file);
        }else{
            JOptionPane.showMessageDialog(null, "没有找到升级文件");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DevicePanel;
    private javax.swing.JTextField FileBinPath;
    private javax.swing.JTable FileHeadTable;
    private javax.swing.JList InfoList;
    private javax.swing.JButton OpenFile;
    private javax.swing.JScrollPane eiaTablePane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
