/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.common;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import nahon.comm.event.Event;
import nahon.comm.event.EventListener;
import nahon.comm.faultsystem.LogCenter;

/**
 *
 * @author chejf
 */
public class LogPane extends javax.swing.JPanel {

    /**
     * Creates new form WorkPane
     */
    public LogPane() {
        initComponents();

        this.List_log.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList jlist, Object e, int i, boolean bln, boolean bln1) {
                super.getListCellRendererComponent(jlist, e, i, bln, bln1);
                if ((i + 1) % 2 == 0) {
                    //偶数行时的颜色
                    setBackground(Color.WHITE);
                } else if ((i + 1) % 2 == 1) {
                    //设置单数行的颜色
                    setBackground(new Color(192, 192, 192, 140));
                }

                return this;
            }
        });

        dlm = new DefaultListModel();
        this.List_log.setModel(dlm);
        LogCenter.Instance().RegisterLogEvent(new EventListener<Level>() {
            @Override
            public void recevieEvent(Event<Level> event) {
                java.awt.EventQueue.invokeLater(() -> {
                    PrintLog(event.Info().toString());
                });
            }
        });
    }

    private DefaultListModel dlm;

    public void PrintLog(String log) {
        dlm.addElement(new SimpleDateFormat("hh:mm:ss:  ").format(new Date()) + log);
        // 刷新左边JList窗口
        this.List_log.setSelectedIndex(dlm.getSize() - 1);
        this.List_log.ensureIndexIsVisible(dlm.getSize() - 1);

    }

    public void ClearLog() {
        dlm.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        List_log = new javax.swing.JList<>();

        List_log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(List_log);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List_log;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
