/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.binfactory;

import forge.bill.platform.ForgeSystem;
import forge.form.common.InitPaneHelper;
import forge.bill.data.UpdateFileHead;
import forge.bill.control.EiaBuilder;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.TableCellEditor;
import nahon.comm.faultsystem.LogCenter;

/**
 *
 * @author jiche
 */
public class BinfileMakeForm extends javax.swing.JPanel {

    private ArrayList<File> inputfile = new ArrayList();
    private java.awt.Frame parent = null;

    /**
     * Creates new form BinfileMakeForm
     */
    public BinfileMakeForm(java.awt.Frame parent) {
        this.parent = parent;
        initComponents();

        this.initInternalEiaTable();
        FileHeadTable.setModel(new BinFileHeadModel(new UpdateFileHead()));
    }

    private JComboBox devnamelist;

    //初始化eia框
    private void initInternalEiaTable() {
        //设置默认设备名称下拉列表
        devnamelist = new JComboBox();
        for (EiaBuilder.devinfo tmpinfo : EiaBuilder.GetInstance().GetList()) {
            devnamelist.addItem(tmpinfo.devname);
        }

        devnamelist.setEditable(true);
        devnamelist.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    //重新选择设备名称后,更新设备表格中设备名称
                    UpdateFileHead filehead = ((BinFileHeadModel) FileHeadTable.getModel()).GetFileHead();
                    filehead.DeviceName = devnamelist.getSelectedItem().toString();
                    FileHeadTable.setModel(new BinFileHeadModel(filehead));
                }
            }
        });

        //更新eia信息框
        this.FileHeadTable = new JTable() {
            @Override
            public TableCellEditor getCellEditor(int row, int column) {
                if (row == 0 && column == 1) {
                    return new DefaultCellEditor(devnamelist);
                } else {
                    return super.getCellEditor(row, column);
                }
            }
        };

        this.eiaTablePane.setViewportView(FileHeadTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrowerFile = new javax.swing.JButton();
        MakeFile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        eiaTablePane = new javax.swing.JScrollPane();
        FileHeadTable = new javax.swing.JTable();
        CleanFile = new javax.swing.JButton();
        Button_Canncel = new javax.swing.JButton();

        BrowerFile.setText("增加bin");
        BrowerFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowerFileActionPerformed(evt);
            }
        });

        MakeFile.setText("开始压缩");
        MakeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeFileActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "文件信息", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setToolTipText("");

        FileHeadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        eiaTablePane.setViewportView(FileHeadTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eiaTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(eiaTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        CleanFile.setText("清除");
        CleanFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanFileActionPerformed(evt);
            }
        });

        Button_Canncel.setText("取消");
        Button_Canncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CanncelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MakeFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BrowerFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_Canncel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CleanFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrowerFile)
                    .addComponent(CleanFile))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakeFile)
                    .addComponent(Button_Canncel)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BrowerFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowerFileActionPerformed
        String filepath = InitPaneHelper.GetFilePath(".bin");

        if (filepath == null) {
            return;
        }

        //增加输入文件
        File file = new File(filepath);
        if (file.exists()) {
            this.inputfile.add(file);
            LogCenter.Instance().PrintLog(Level.INFO, "添加新文件-" + this.inputfile.size()
                    + filepath);
            UpdateFileHead filehead = ((BinFileHeadModel) FileHeadTable.getModel()).GetFileHead();
            filehead.BinFileNumbier = this.inputfile.size();
            FileHeadTable.setModel(new BinFileHeadModel(filehead));
        }
    }//GEN-LAST:event_BrowerFileActionPerformed


    private void MakeFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeFileActionPerformed
        String filepath = InitPaneHelper.GetFilePath(".nuf");

        if (filepath == null) {
            return;
        }else{
            if(!filepath.endsWith(".nuf")){
                filepath += ".nuf";
            }
        }

        //开始制作进程
        ForgeSystem.GetInstance().GetControlCenter().GetUpdateBean().GetUpdateBuilder().CompressBinFiles(
                inputfile.toArray(new File[0]),
                new File(filepath),
                ((BinFileHeadModel) this.FileHeadTable.getModel()).GetFileHead());
        //清除输入file
        inputfile.clear();
    }//GEN-LAST:event_MakeFileActionPerformed

    private void clearinput() {
        for (int i = 0; i < inputfile.size(); i++) {
            File file = inputfile.get(i);
            LogCenter.Instance().PrintLog(Level.INFO, "删除文件-" + (i + 1)
                    + file.getAbsolutePath());
        }
        inputfile.clear();
        UpdateFileHead filehead = ((BinFileHeadModel) FileHeadTable.getModel()).GetFileHead();
        filehead.BinFileNumbier = 0;
        FileHeadTable.setModel(new BinFileHeadModel(filehead));
    }

    //清除所有输入
    private void CleanFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanFileActionPerformed
        this.clearinput();
    }//GEN-LAST:event_CleanFileActionPerformed

    private void Button_CanncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CanncelActionPerformed
        ForgeSystem.GetInstance().GetControlCenter().GetUpdateBean().GetUpdateBuilder().Cancel();
    }//GEN-LAST:event_Button_CanncelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowerFile;
    private javax.swing.JButton Button_Canncel;
    private javax.swing.JButton CleanFile;
    private javax.swing.JTable FileHeadTable;
    private javax.swing.JButton MakeFile;
    private javax.swing.JScrollPane eiaTablePane;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
